import { Change, Changelog, Post } from '../../../types/Post';
import ahliObs1 from '../../../assets/ahliObs/1.avif';
import ahliObs3 from '../../../assets/ahliObs/3.avif';
import ahliObs5 from '../../../assets/ahliObs/5.avif';
import ahliObs11 from '../../../assets/ahliObs/11.avif';
import ahliObs14 from '../../../assets/ahliObs/14.avif';
import ahliObs15 from '../../../assets/ahliObs/15.avif';
import ahliObs17 from '../../../assets/ahliObs/17.avif';
import ahliObs18 from '../../../assets/ahliObs/18.avif';
import ahliObs20 from '../../../assets/ahliObs/20.avif';
import ahliObs21 from '../../../assets/ahliObs/21.avif';
import ahliObs22 from '../../../assets/ahliObs/22.avif';
import ahliObs23 from '../../../assets/ahliObs/23.avif';
import ahliObs24 from '../../../assets/ahliObs/24.avif';
import ahliObs26 from '../../../assets/ahliObs/26.avif';
import ahliObs27 from '../../../assets/ahliObs/27.avif';
import ahliObs30 from '../../../assets/ahliObs/30.avif';
import ahliObs31 from '../../../assets/ahliObs/31.avif';
import ahliObs32 from '../../../assets/ahliObs/32.avif';
import ahliObs33 from '../../../assets/ahliObs/33.avif';
import ahliObs34 from '../../../assets/ahliObs/34.avif';
import ahliObs35 from '../../../assets/ahliObs/35.avif';
import ahliObs36 from '../../../assets/ahliObs/36.avif';
import ahliObs37 from '../../../assets/ahliObs/37.avif';
import ahliObs38 from '../../../assets/ahliObs/38.avif';
import ahliObs39 from '../../../assets/ahliObs/39.avif';
import ahliObs40 from '../../../assets/ahliObs/40.avif';
import ahliObs41 from '../../../assets/ahliObs/41.avif';
import ahliObs43 from '../../../assets/ahliObs/43.avif';
import ahliObs44 from '../../../assets/ahliObs/44.avif';
import ahliObs45 from '../../../assets/ahliObs/45.avif';
import ahliObs46 from '../../../assets/ahliObs/46.avif';
import ahliObs49 from '../../../assets/ahliObs/49.avif';
import ahliObs50 from '../../../assets/ahliObs/50.avif';
import ahliObs51 from '../../../assets/ahliObs/51.avif';
import ahliObs52 from '../../../assets/ahliObs/52.avif';
import ahliObs53 from '../../../assets/ahliObs/53.avif';
import ahliObs54 from '../../../assets/ahliObs/54.avif';
import ahliObs55 from '../../../assets/ahliObs/55.avif';
import ahliObs56 from '../../../assets/ahliObs/56.avif';
import ahliObs59 from '../../../assets/ahliObs/59.avif';
import ahliObs67 from '../../../assets/ahliObs/67.avif';
import ahliObs68 from '../../../assets/ahliObs/68.avif';
import ahliObs69 from '../../../assets/ahliObs/69.avif';
import ahliObs70 from '../../../assets/ahliObs/70.avif';
import ahliObs71 from '../../../assets/ahliObs/71.avif';
import ahliObs72 from '../../../assets/ahliObs/72.avif';
import ahliObs73a from '../../../assets/ahliObs/73a.avif';
import ahliObs73b from '../../../assets/ahliObs/73b.avif';
import ahliObs74a from '../../../assets/ahliObs/74a.avif';
import ahliObs74b from '../../../assets/ahliObs/74b.avif';
import ahliObs75 from '../../../assets/ahliObs/75.avif';

export const ahliObsChangelog: Post[] = [
  {
    id: '75',
    title: '0.75 - Patch Compatibility and Fixes',
    image: ahliObs75,
    createdAt: '2nd January 2024',
    download:
      'https://www.dropbox.com/scl/fi/5fuwxl26ttl9e2dy5tmtj/AhliObs-0.75.StormInterface?rlkey=bco85hmdb87011frvkp4yursr&dl=1',
    version: '0.75',
    date: '2nd January 2024',
    changes: [
      new Change('added compatibility with Heroes 2.55.4.91418', [
        'fixed health bars in top panel being too large',
        "fixed DVa Mech's energy color in top panel and simplified the detection for all heroes",
        'added three health bars for Lost Vikings into top panel',
        "added a second health bar for Rexxar's Misha",
        "removed now unnecessary workaround for DVa's Mech HP in top panel",
        "fixed DVa's portrait not displaying her in Mech",
        new Change("improved Dragon Shire's Dragon Knight UI", [
          "controller's portrait now looks similar to Volkovskaya's Robot's one",
          'fixed appearance of Lost Vikings',
        ]),
      ]),
      "fixed visual appearance of Maiev's Naisha's Memento button icon in the selected unit's panel",
      new Change("fixed some issues with Battlefield of Eternity's map objective UI:", [
        "fixed lane Immortal's health bar starting behind the icon so the last few percentages of life are not visible",
        "fixed Duel UI swapping positions in red player's vision",
        "fixed lane Immortal's icon disappearing when switching player vision",
        'fixed issues with crossout image animations of an earlier duel appearing',
        'fixed health labels not using colorblind colors when option is enabled',
      ]),
      "fixed Sky Temple's shrine icons having wrong color in red player's vision",
    ],
  },
  {
    id: '74',
    title: '0.74 - fixes and polish',
    image: [ahliObs74a, ahliObs74b],
    createdAt: '2nd March 2022',
    download: 'https://www.dropbox.com/s/tv931liwl3a3mjs/AhliObs%200.74.StormInterface?dl=1',
    version: '0.74',
    date: '2nd March 2022',
    changes: [
      'fixed self healing and heal other stats in bottom panel referencing the damage taken values instead of its actual value',
      "fixed the colors during Tomb of the Spider Queen's Webweaver UI while being in red team's vision",
      "fixed appearance of kill/quest notifications and some map objective UIs when the selected unit's player vision button is held down (v shortcut)",
      'fixed the F ability button (e.g. Nuke) being visible on maps that do not use it',
      "fixed the F ability button's cooldown label being drawn next to the button instead of on top of it",
      'talent selection UI (accessible only in player vision via the usual hotkey) is now muted',
      "fix most issues with Garden of Terror's map mechanic UI elements regarding vision and replay time jumps",
      "re-implemented Murky and Thrall's hero UI to make it appear in everyone vision and only if that hero is the sole selected unit",
      "fixed Skull Golem health bars and its skull counter's appearance during red team vision on Haunted Mines",
    ],
  },
  {
    id: '73',
    title: '0.73 - charge and k',
    image: [ahliObs73a, ahliObs73b],
    createdAt: '23rd January 2022',
    download: 'https://www.dropbox.com/s/rbwt2ahfqfvgu35/AhliObs%200.73.StormInterface?dl=1',
    version: '0.73',
    date: '23rd January 2022',
    changes: [
      new Change('added a charge counter for heroics in the top panel supporting:', [
        'Brightwing, Lunara, Garrosh, Stukov, DVa, Rangaros, Zagara, Nova, Valla, Artanis, Muradin and Deckard',
      ]),
      new Change('changed bottom panel:', [
        'stats are now displayed showing values in k',
        'role icons from support to healer and from warrior to tank',
        'column title background image is now less transparent',
      ]),
      "added Keep icons to the Core's health bars in the top panel on Alterac Pass",
      "fixed blue team's heroic icons being displayed cut off in the top panel",
      'fixed ability button border images being cut off in the bottom left panel',
      "fixed activatable talent's ability button's image being drawn outside the border image in the bottom left panel",
      "fixed Garden of Terror's map mechanic UI's seed icons not always being displayed",
      'fixed a gap appearing in hero UIs for Fenix and Junkrat',
      "Leoric's ghost won't display a low health label anymore",
      new Change(
        'exposed a setting to the Settings Editor that allows hiding player names near captured camps and destroyed forts',
        ['please update the Settings Editor as this is a new feature']
      ),
    ],
  },
  {
    id: '72',
    title: '0.72 - fixes & improvements',
    image: ahliObs72,
    createdAt: 'Mar 25, 2021, 4:42 PM',
    updatedAt: 'Mar 25, 2021, 4:45 PM',
    download: 'https://www.dropbox.com/s/o8xuhpdveczmw1h/AhliObs%200.72.StormInterface?dl=1',
    version: '0.72',
    date: '25th March 2021',
    changes: [
      new Change("added a health and energy bar for DVa's Mech (big thanks to Spazzo for the research)", [
        'the portrait changes to indicate what state the health bar refers to',
        "Please note that clicking the portrait still won't select DVa's Mech",
      ]),
      'added globally visible stack counter to the status bars of Raynor, Orphea, Valeera and Alexstrasza (only Gift Of Life)',
      "added indicator on Alexstrasza's health bar for her level 1 talent Live and Let Live",
      "added Misha to Rexxar's top panel portrait similar to the Lost Vikings",
      new Change('bottom panel changes:', [
        'fixed bottom panel showing self-healing instead of damage-taken in the role column with the shield icon',
        'removed the glow of icons in the role column making it hard to read on high grapphic settings',
      ]),
      new Change(
        "kill log entries' background animation is now respecting colorblindness (it was caused by a bug in Blizz's UI code clearing all filters including the colorblind one)",
        [
          "Chen's suicide with Stagger is now correctly displayed with the animation and sword indicating the benefiting team",
          new Change('vision changes no longer causes wrong colors to be displayed in the kill log', [
            'Please note that multiple entries will still stack on vision change',
          ]),
        ]
      ),
      'altered the level number within the tooltip of talents in the bottom panel to improve performance',
      'fixed Varian level 4 heroic cooldowns appearing player colored',
      `removed the notification's default texts to avoid "[Notification Text]" to appear on screen`,
      'vision changes via shortcuts 1-0, E and O or using the pulldown are now silent',
      'removed buffs being displayed when selected unit info is hidden',
      new Change("exposed more settings to Ahli's settings editor (separate tool) to:", [
        'force hero/player names above healthbars',
        'hide textual kill notifications',
        'hide chat at game start',
        'hide unit info at the game start',
        'hide observer controls at game start in replays',
      ]),
      "the portrait and the unit details will now show Cho'Gall's name instead of the mixed player name",
      'added the Unit Type to the selected unit details panel',
      "fixed observer control's pulldown arrow facing downwards",
      'made the map objective UI of Alterac Pass more resistant to player vision changes',
    ],
  } as Changelog,
  {
    id: '71',
    title: '0.71 - Hogger - 2.53.0.83086',
    image: ahliObs71,
    createdAt: '8th December 2020',
    download: 'https://www.dropbox.com/s/hjm0z9tmh15x365/AhliObs%200.71.StormInterface?dl=1',
    version: '0.71',
    date: '8th December 2020',
    changes: [
      new Change('added compatibility with patch 2.53.0.83086 Hogger', [
        'added low hp label, energy bars and player name toggle to Hogger',
      ]),
      "fixed right team's extra cooldown's label (used to be medaillon CD) appearing behind the icon for some users (animation breaks order among frames of the same renderPriority)",
      "fixed unit details panel's unit name not always being displayed",
    ],
  } as Changelog,
  {
    id: '70',
    title: '0.70 - Polishing the Medaillon',
    image: ahliObs70,
    createdAt: '7th November 2020',
    download: 'https://www.dropbox.com/s/goek4cyy8m5sdqy/AhliObs%200.70.StormInterface?dl=1',
    version: '0.70',
    date: '7th November 2020',
    changes: [
      new Change('the extra cooldowns in the top panel will not disappear anymore during death', [
        "added Gazlowe's orange scrap bar and low health label",
        'the icon shrinks by 25% after the heroic becomes visible',
        "Baleog's death timer now adjusts its position to remain readable",
        'death timers will now move sideways when the the heroic or an extra cooldown becomes active',
      ]),
      "the Dragon Knight's hero is now visible above the minimap; removed its portrait overlay",
      "the default UI's panel that shows the stats of a clicked unit is now permanently hidden",
    ],
  } as Changelog,
  {
    id: '69',
    title: '0.69 - Very Nice! - 2.52.0',
    image: ahliObs69,
    createdAt: '25th October 2020',
    download: 'https://www.dropbox.com/s/xx0zel5fa6dd531/AhliObs%200.69.StormInterface?dl=1',
    version: '0.69',
    date: '25th October 2020',
    changes: [
      new Change('added compatibility with patch 2.52.0:', ["added Gazlowe's orange scrap bar and low health label"]),
      "added Gladiator's Medallion / Deathwing's Bellowing Roar cooldown to the hero portraits in the top panel",
      'added hotkey to toggle player names: Control+Alt+N (visible by default)',
      "added the level to the background of the talents' tooltips in the bottom panel",
      "added a workaround for Blizzard's bug causing talent panel to be opened automatically once a selected hero picks a talent to Everyone view",
      "fixed Varian's Colossus Smash cooldown being displayed team-colored",
      "fixed Deathwing's Cataclysmn icon of the top panel being too large",
      "fixed Tracer's circular charge progress texture not being displayed in the top panel (weird engine bug; fix via diff texturecoords)",
      'fixed healing fountain state being visible when an uncaptured merc or boss was selected',
      'fixed Dragon Knight hero icon colorblind border remaining red instead of switching to orange',
    ],
  } as Changelog,
  {
    id: '68',
    title: '0.68 - Bug Fixes - 2.50.0.79155',
    image: ahliObs68,
    createdAt: '26th April 2020',
    download: 'https://www.dropbox.com/s/jdgt11u1hg8kkwv/AhliObs%200.68.StormInterface?dl=1',
    version: '0.68',
    date: '26th April 2020',
    changes: [
      'Deathwing will now always show Cataclysm in the top panel',
      "fixed Deathwing's carried item overlapping with his status bar icon",
      "fixed Sonya's displaying a blue mana bar in top panel instead of an orange one",
      "fixed D.Va's self destruct button overlay's size",
      "added low health label to Whitemane's and Leoric's Status bars",
      'fixed improved quest icon tooltips for the left team in bottom panel',
      "fixed Varian's Colossus Smash heroic not being darkened in top panel",
    ],
  } as Changelog,
  {
    id: '67',
    title: '0.67 - Deathwing - 2.49.0.77525',
    image: ahliObs67,
    createdAt: '7th April 2020',
    download: 'https://www.dropbox.com/s/xxsuo5cvgbt42m5/AhliObs%200.67.StormInterface?dl=1',
    version: '0.67',
    date: '7th April 2020',
    changes: [
      new Change('added compatibility to patch 2.49.0.77525 Deathwing and 2.50.0.79033 PTR:', [
        'Deathwing received a low life label',
        'Deathwing received red energy bars',
        "fixed Deathwing's dragon icon around the hero portrait",
      ]),
      "added the colorblind-option to borders of hero icons of heroes that are inside other units (e.g. inside Blaze's Bunker)",
      'removed unused code from talent notifications',
      'improved tooltip of baseline quests in bottom panel of the red team (blue team still showing the old tooltip for unknown reasons)',
      'fixed Lost Viking portraits in top panel not darkening and not respecting the colorblind option',
      "corrected the color of the energy bars of Chen, Auriel, Valeera, Lt. Morales and added segments to Junkrat's and Volskaya Robot's one",
    ],
  } as Changelog,
  {
    id: '66',
    title: '0.66 - Qhira - 2.47.0.75484',
    createdAt: '6th August 2019',
    download: 'https://www.dropbox.com/s/kyxbxr9kmn9px3l/AhliObs%200.66.StormInterface?dl=1',
    version: '0.66',
    date: '6th August 2019',
    changes: [
      new Change('added compatibility to patch 2.47.0.75410 Qhira PTR:', [
        "added low hp label into Qhira's status bar",
      ]),
    ],
  } as Changelog,
  {
    id: '65',
    title: '0.65 - Hotfix - 2.44.0.72880',
    createdAt: '5th April 2019',
    download: 'https://www.dropbox.com/s/qn4nwo6n88odemx/AhliObs%200.65.StormInterface?dl=1',
    version: '0.65',
    date: '5th April 2019',
    changes: ['fixed separator images in the map score panel at the top becoming visible'],
  } as Changelog,
  {
    id: '64',
    title: '0.64 - Hotfix - 2.44.0.72880',
    createdAt: '1st April 2019',
    download: 'https://www.dropbox.com/s/mssslp1hmietcvx/AhliObs%200.64.StormInterface?dl=1',
    version: '0.64',
    date: '1st April 2019',
    changes: [
      'fixed separator images in bottom panel stats panel becoming visible',
      'fixed nuke button altering its size and position when entering player vision',
    ],
  } as Changelog,
  {
    id: '63',
    title: '0.63 - Caldeum Complex - 2.44.0.72880',
    createdAt: '24th March 2019',
    download: 'https://www.dropbox.com/s/xw3x0hxnazxry53/AhliObs%200.63.StormInterface?dl=1',
    version: '0.63',
    date: '24th March 2019',
    changes: [
      new Change('added compatibility to patch 2.44.0.72880 - Caldeum Complex', [
        'hid new separator images added to the heroleaderpanel',
        'fixed leaderpanel stats showing a hiven instead of a zero and not hiding when zero (e.g. damage taken)',
        'added support for new negative armor limit of -75',
      ]),
    ],
  } as Changelog,
  {
    id: '62',
    title: '0.62 - Imperius - 2.42.2.71931',
    createdAt: '10th February 2019',
    download: 'https://www.dropbox.com/s/et3k0xctnxse1w1/AhliObs%200.62.StormInterface?dl=1',
    version: '0.62',
    date: '10th February 2019',
    changes: [
      new Change('added compatibility to patch 2.42.2.71931 - Imperius', [
        "fixed F-ability button's visuals",
        'fixed armor buff icons in unit details',
      ]),
      new Change('improved support for Varian', [
        "Varian's talents are now properly highlighted in the bottom panel (heroic on level 4, standard on 10)",
        "Varian's heroic (on level 4) is now appearing in the top panel along with its cooldown",
      ]),
    ],
  } as Changelog,
  {
    id: '61',
    title: '0.61 - Orphea - 2.39.2.69823',
    createdAt: '15th November 2018',
    download: 'https://www.dropbox.com/s/f8o0pqsek9fdoca/AhliObs%20v0.61.StormInterface?dl=1',
    version: '0.61',
    date: '15th November 2018',
    changes: [
      new Change('added compatibility to patch 2.39.2.69823 - Orphea', [
        'fixed ability buttons',
        'fixed Maiev not showing low HP label',
        "fixed Zarya's weapon boost percentage label always displaying 0%",
        "fixed F-ability button (e.g. Warhead Junction's Nuke button)",
        "fixed Tracer's heroic cooldown graphics (button and heroic cooldown)",
        "removed Garden of Terror's hero portrait overlay",
      ]),
    ],
  } as Changelog,
  {
    id: '60',
    title: '0.60 - Whitemane - 2.36.0.67143',
    createdAt: '8th August 2018',
    download: 'https://www.dropbox.com/s/snisqlyc6teq5s5/AhliObs%20v.0.60.StormInterface?dl=1',
    version: '0.60',
    date: '8th August 2018',
    changes: [
      new Change('added compatibility to patch 2.36.0.67143 - Whitemane', [
        'fixed black portraits in top bar',
        'fixed information of a selected unit not being visible',
      ]),
      'added missing low health label of Fenix, D.Va (Pilot), Stitches and Misha',
    ],
  } as Changelog,
  {
    id: '59',
    title: '0.59 - Echoes of Alterac & Yrel - 2.34.0.65579',
    image: ahliObs59,
    createdAt: '13th June 2018',
    download: 'https://www.dropbox.com/s/vapa9xybct24nj3/AhliObs%200.59.StormInterface?dl=1',
    version: '0.59',
    date: '13th June 2018',
    changes: [
      new Change('added compatibility to patch 2.34.0.65579 - Echoes of Alterac & Yrel', [
        'fixed information of a selected unit not being visible',
        'added absorbing buff to unit details',
      ]),
      'removed rounding from damage tooltip to be able to show 1 fraction digit',
      'fixed unit names not appearing in two lines on the portrait like Vanndar Stormpike',
    ],
  } as Changelog,
  {
    id: '58',
    title: '0.58 - Nexomania Event - 2.32.1.64657',
    createdAt: '23rd May 2018',
    download: 'https://www.dropbox.com/s/zhhqlcqnjj0wga6/AhliObs%200.58.StormInterface?dl=1',
    version: '0.58',
    date: '23rd May 2018',
    changes: [
      new Change('added compatibility to patch 2.32.1.64657 - Nexomania Event', [
        'restored visibility of hero UIs',
        'fixed team level font size',
      ]),
      'restored visibility of structure damage in unit details panel',
      'added tooltip to the weapon damage near the portrait showing base damage and damage vs heroes, minions, and structures',
      'fixed color of the recharging part of the blue mana bar',
      "fixed color of Valeera's console mana bar",
      "modified top panel's health bars to use a color set supporting colorblindness",
    ],
  } as Changelog,
  {
    id: '57',
    title: '0.57 - Deckard Cain - 2.32.1.64657',
    createdAt: '15th May 2018',
    download: 'https://www.dropbox.com/s/vjaee3t5lw2gb23/AhliObs%200.57b.StormInterface?dl=1',
    version: '0.57',
    date: '15th May 2018',
    changes: [
      new Change('added compatibility to patch 2.32.1.64657 - Deckard Cain release', [
        'fixed unit details panel not showing any information',
        'fixed unit name not appearing above the portrait',
        'fixed health/mana bar colors to be usable again',
      ]),
      'fixed icon of slow debuffs in unit details',
      "fixed Control+E not hiding white vertical lines in the core's health bars of the top panel",
      "fixed Medivh's Portal's colors via reverting to Blizz's new, orange default look",
    ],
  } as Changelog,
  {
    id: '56',
    title: '0.56 - Blaze - 2.29.7.61129',
    image: ahliObs56,
    createdAt: '9th January 2017',
    download: 'https://www.dropbox.com/s/u9nnavwr2y4ovmq/AhliObs%200.56.StormInterface?dl=1',
    version: '0.56',
    date: '9th January 2017',
    changes: [
      new Change('added compatibility to patch 2.29.7.61129 - Blaze release', [
        "removed mouse highlight of Blaze's bunker",
        'hid heroic icon cooldown image',
      ]),
      'fixed icon of slow debuffs in unit details',
      "fixed icon of the 'protected' status showing the invulnerable icon in unit details",
      "adjusted Tracer's mana bar color to match Blizzard's definition",
      "added workaround to fix Sgt Hammer's portrait being transparent",
      "fixed Control+C hiding the selected unit's portrait",
    ],
  } as Changelog,
  {
    id: '55',
    title: '0.55 - Alexstrasza - 2.29.0.58657',
    image: ahliObs55,
    createdAt: '14th November 2017',
    download: 'https://www.dropbox.com/s/uhbkic9jcp70r0m/AhliObs%200.55.StormInterface?dl=1',
    version: '0.55',
    date: '14th November 2017',
    changes: [
      new Change('added compatibility to patch 2.29.0.58657 - Alexstrasza release', [
        'fixed armor value readings',
        'hid voice chat aspects in the bottom panel in case they were visible',
      ]),
      "bottom panel's time spent dead does not highlight the highest value anymore",
      new Change(
        "fixed ctrl+E not hiding the kill log, hero UI, 'chose a talent' notifications and the talent selection UI",
        ["known problem: it still shows 'new talent' above the portrait because I don't know which frame creates this"]
      ),
      'fixed ctrl+E creating quest completion notifications',
      'fixed quest "!" appearing behind the portraits when the bottom panel is shown',
    ],
  } as Changelog,
  {
    id: '54',
    title: '0.54 - Junkrat - Patch 2.28.3.58623',
    image: ahliObs54,
    createdAt: '17th October 2017',
    download: 'https://www.dropbox.com/s/8rjpgmexyw87ri7/AhliObs%200.54.StormInterface?dl=1',
    version: '0.54',
    date: '17th October 2017',
    changes: [
      'added new armor and healing icons into the unit details',
      new Change('added compatibility to patch 2.28.3.58623 - Junkrat release', [
        "added Junkrat's colored mana bar",
        'fixed handling of finished, unlimited quests',
        "fixed stack labels overlapping with talent texts in bottom panel's talent tooltips",
        "known problem: Junkrat's hero UI will only work properly in player vision similar to other hero UIs",
        'removed several duplicated hero UIs',
      ]),
      'selecting Tracer shows her ammo bar again',
    ],
  } as Changelog,
  {
    id: '53',
    title: '0.53 - Ana PTR - Patch 2.28.0.57547',
    image: ahliObs53,
    createdAt: '20th September 2017',
    download: 'https://www.dropbox.com/s/p7numi96ecm90pe/AhliObs%200.53.StormInterface?dl=1',
    version: '0.53',
    date: '20th September 2017',
    changes: [
      new Change('added compatibility to patch 2.28.0.57547 - Ana PTR', [
        "added Ana's hero UI",
        "added Triglav protector's colored mana bar when selected",
        'fixed player context menu buttons',
        new Change(
          "fixed Jaina's ice block progress bar size and appearance on all heroes using the same ability slot",
          ['known problem: it is visible twice when there are two Jainas']
        ),
      ]),
      'fixed super long quest stack counts being truncated in the bottom panel, now they shrink instead',
      "fixed Genji's Dragon Claw progress bar size and appearance on all heroes using the same ability slot",
      "fixed Garrosh's Body Check button highlight's appearance on all heroes using the same ability slot",
      'added notifications for baseline quests',
      'fixed the portrait being visible without further information, e.g. when two units were selected or during replay time jumps',
    ],
  } as Changelog,
  {
    id: '52',
    title: "0.52 - Kel'Thuzad - Patch 2.27.3.56859",
    image: ahliObs52,
    createdAt: '11th September 2017',
    download: 'https://www.dropbox.com/s/g2x5man6iqovr7n/AhliObs%200.52.StormInterface?dl=1',
    version: '0.52',
    date: '11th September 2017',
    changes: [
      new Change("added compatibility to patch 2.27.3 - Kel'Thuzad", [
        "added heroUI for Kel'Thuzad, Leoric and Chromie",
        "fixed Butcher's hero UI position",
        'changed Lt. Morales mana bar color from blue to yellow',
        new Change('added base line quests to the bottom panel', [
          'known problem: no new tooltip style',
          'known problem: no notification on the right side',
        ]),
        'fixed kill log icon displaying a white square',
        'fixed protected buff in unit details',
      ]),
    ],
  } as Changelog,
  {
    id: '51',
    title: '0.51 - Garrosh - Patch 2.27.0.56175',
    image: ahliObs51,
    createdAt: '9th August 2017',
    download: 'https://www.dropbox.com/s/qa4197oxx8auxf1/AhliObs%200.51.StormInterface?dl=1',
    version: '0.51',
    date: '9th August 2017',
    changes: [
      "fixed player vision being able to switch bottom panel's teams",
      'new map score background image',
      'talent tooltips now also show a quest progress bar and max stacks',
      'improved colorblind support',
      "hid chat's drag button, fixed chat bar not being on screen",
      'the talent selection panel (req. player vision) now hides the unit details panel as long as it is open',
    ],
  } as Changelog,
  {
    id: '50',
    title: '0.50 - Garrosh - Patch 2.27.0 PTR',
    image: ahliObs50,
    createdAt: '31st July 2017',
    download: 'https://www.dropbox.com/s/cjsv8dwjbomk5g1/AhliObs%200.50.StormInterface?dl=1',
    version: '0.50',
    date: '31st July 2017',
    changes: [
      new Change('talent notifications:', [
        'now displays up to 5 notifications at once',
        'new look, removed player name',
        'quest notifications have a visual indicator',
      ]),
      'fixed quest progress bar not being visible in bottom panel',
      new Change('added compatibility to patch 2.27.0 - Garrosh', [
        "added Garrosh's hero UI",
        're-added low life health label to Auriel',
        're-hid death recap button',
        'updated icon and color of sleeping debuff in unit details',
        'added colorblind texture variation to hindered healing debuff in unit details',
        'fixed portrait of a selected hero not appearing',
        new Change('re-fixed kill log panel colors of victims when switching player vision', [
          'known problem: entries and potraits can disappear when player vision changes',
        ]),
      ]),
    ],
  } as Changelog,
  {
    id: '49',
    title: '0.49 - Stukov - Patch 2.26.3',
    image: ahliObs49,
    createdAt: '11th July 2017',
    download: '',
    version: '0.49',
    date: '11th July 2017',
    changes: [
      'fixed UI-hiding hotkeys not hiding the talent notifications panel',
      'added shortcut "Control + T" to toggle the talent notifications panel',
      'fixed missing hotkey of toggling the chat for the settings editor',
      'fixed D.Va and Samuro not showing a health value on her health bar when below 15% health for 1 second',
      new Change('redesigned bottom left area showing information about the selected unit:', [
        'shows portrait',
        'shows hardened focus indicator',
        'some hero UIs have been removed to match the actual hero UI of the players',
        'shows spell and physical armor',
        'life bar is team colored',
      ]),
      new Change('added compatibility to patch 2.26.3 - Stukov', ["added Stukov's hero UI"]),
    ],
  } as Changelog,
  {
    id: '48',
    title: "0.48 - adjusted Zul'jin's Guillotine Damage in his hero UI - 2.26.1",
    createdAt: '28th June 2017',
    download: 'https://www.dropbox.com/s/cxbu4w4grb34hbv/AhliObs%200.48.StormInterface?dl=1',
    version: '0.48',
    date: '28th June 2017',
    changes: [
      "adjusted Zul'jin's Guillotine damage formula used in his hero UI to reflect today's balance patch 2.26.1",
      'fixed orange, transparent dot image that could appear above the portraits',
    ],
  } as Changelog,
  {
    id: '47',
    title: '0.47 - Tool for Editable Settings',
    createdAt: '19th June 2017',
    download: 'https://www.dropbox.com/s/o90v0t7x2kzvxwg/AhliObs%20v.0.47.StormInterface?dl=1',
    version: '0.47',
    date: '19th June 2017',
    changes: ['removed tooltips in talent notifications', 'added compatibility to Observer UI Settings Editor Alpha'],
  } as Changelog,
  {
    id: '46',
    title: '0.46 - Malthael',
    image: ahliObs46,
    createdAt: '5th June 2017',
    download: 'https://www.dropbox.com/s/pq0hqbrhdqs4il7/AhliObs%20v.0.46.StormInterface?dl=1',
    version: '0.46',
    date: '5th June 2017',
    changes: [
      new Change("added compatibility to Mathael's PTR patch 2.26:", [
        "fixed bottom panel's heroic border",
        'added sleeping debuff into hero details, fixed other ones',
        'disabled On-Fire effect for the damage-taken stat in bottom panel',
      ]),
      'added notifications to show talent picks and quest completion',
    ],
  } as Changelog,
  {
    id: '45',
    title: '0.45 - Fixes & Improvements',
    image: ahliObs45,
    createdAt: '27th May 2017',
    download: 'https://www.dropbox.com/s/ugcbucqghiipjvk/AhliObs%20v.0.45.StormInterface?dl=1',
    version: '0.45',
    date: '27th May 2017',
    changes: [
      'fixed death time label disappearing when unlocking heroic',
      'added hero UI for Alarak showing Sadism label and tooltip (no progress bar as it does not work)',
      'added death time label for each of the Lost Vikings',
      'removed silenced icon and tooltip from bottom panel',
    ],
  } as Changelog,
  {
    id: '44',
    title: '0.44 - D.Va',
    image: ahliObs44,
    createdAt: '17th May 2017',
    download: 'https://www.dropbox.com/s/r550kjy18cvva7k/AhliObs%20v.0.44.StormInterface?dl=1',
    version: '0.44',
    date: '17th May 2017',
    changes: [
      new Change('added compatibility to Patch 2.25.4 - D.Va:', [
        new Change("added heroUI for D.Va and Tyrande (except for D.Va's defense matrix UI)", [
          "known problem: D.Va's life and energy bar are hidden while she is in her Mech (currently, there is no way to read data from her Mech as an observer, only her pilot mode is accessible)",
        ]),
        'added pink energy bars for D.Va',
        new Change("bottom panel's role stats now alternate, if healing and damage taken is both valid for a hero", [
          'known problem: some heroes display an empty role box instead of none',
        ]),
        "fixed Medivh's Portal's duration bar being grey instead of orange",
      ]),
      "fixed Tracer's hero UI",
      new Change('unit details panel now shows physical armor vs Heroes, if different from generic armor amount', [
        "for example: Block talent or Brightwing's E adds physical armor only vs hero attacks",
      ]),
      "Medivh's Portal duration bar now adjusts its color in colorblind mode",
      new Change('death timers in top bar were adjusted:', [
        'added an outline',
        'now update properly in replays when you jump to other points of time',
        'fixed portraits appearing darkened while the hero is alive due to replay time jumps',
        'added skull animation on portrait on death',
      ]),
      new Change("fixed victims' portrait color when player vision is switched", [
        'known problem: if the hero was killed by a Mercenary Camp, the color can still appear wrong in player vision',
      ]),
      'doubled animation speed of bottom panel tabs',
    ],
  } as Changelog,
  {
    id: '43',
    title: 'v.0.43 - Genji',
    image: ahliObs43,
    createdAt: '11th May 2017',
    download: 'https://www.dropbox.com/s/pf9m47kxa61jwr1/AhliObs%20v.0.43.StormInterface?dl=1',
    version: '0.43',
    date: '11th May 2017',
    changes: [
      new Change('added compatibility to Heroes 2.0 update:', [
        'added/fixed Genji hero UI',
        'fixed talent borders and visibility in the bottom panel',
        'removed pre-selection indicator (brighter health bar on mouse-over) on payloads on Hanamura',
        "fixed talent tooltip's images being rendered behind the background image",
        '"F" ability button becomes visible for heroes on Hanamura',
      ]),
      'fixed size of "show replays controls" UI button',
      'hid the button holder image to avoid showing a white square',
      "unit names and bottom panel's column names now scale instead of being trunctated when too long",
      'added Chinese and Taiwanese translation of unit info labels thanks to @tinkoliu',
    ],
  } as Changelog,
  {
    id: '42',
    title: 'v.0.42 - Bug Fix',
    image: ahliObs41,
    createdAt: '2nd April 2017',
    download: 'https://www.dropbox.com/s/c6dh5met9p1j91c/AhliObs%20v.0.42.StormInterface?dl=1',
    version: '0.42',
    date: '2nd April 2017',
    changes: [
      'fixed block frame being visible in the bottom panel in live games',
      'fixed XML file compression not being enabled',
    ],
  } as Changelog,
  {
    id: '41',
    title: 'v.0.41 - Balance Patch 24.2',
    image: ahliObs41,
    createdAt: '28th March 2017',
    download: 'https://www.dropbox.com/s/em1ta46c8jiemnc/AhliObs%20v.0.41.StormInterface?dl=1',
    version: '0.41',
    date: '28th March 2017',
    changes: [
      new Change('added compatibility with patch 24.2:', [
        'removed heroic cooldown workaround as Blizzard fixed the problem with this patch',
        'Core Health Towers of Doom does not show the maximum Core life amount anymore (e.g. 12 instead of 12/40)',
      ]),
      "removed tooltip from top bar's heroic icons",
      'hid several off-screen elements to improve performance',
      'bottom panel heroics and storm talents now have a circular alpha mask',
      "bottom panel's talent icons now reset properly when rewinding replays",
    ],
  } as Changelog,
  {
    id: '40',
    title: 'v.0.40 - Probius',
    image: ahliObs40,
    createdAt: '21st March 2017',
    download: 'https://www.dropbox.com/s/7iqmiunykbm3g27/AhliObs%20v.0.40.StormInterface?dl=1',
    version: '0.40',
    date: '21st March 2017',
    changes: [
      new Change('added compatibility to Probius Update:', [
        new Change('top bar changes:', [
          'fixed top area showing all talents',
          new Change('fixed most heroic cooldowns not being shown', [
            "known problem: enemy team's heroics stop updating during player vision",
          ]),
          "fixed ctrl+W hotkey making Blizzard's new small top bar visible",
          'fixed health/mana bars not being resized',
          new Change("fixed Tracer's heroic charge display", [
            'known problem: there is a chance that it appears in the wrong slot, but I assume this is limited to custom games with AI',
          ]),
        ]),
        new Change('bottom panel changes:', [
          'removed "VS" and role icons',
          'fixed talent icons',
          'fixed experience source labels of both teams showing no values',
          "removed player vision's own hero indicator image",
          'removed on fire animations that appeared behind stats',
          'integrated colored background images into talent icons',
          'moved quest progress label to the left corner of the icon',
        ]),
        'moved healing fountain countdown slightly downwards to match the position of the buff icons',
        new Change('unit details panel changes:', [
          'removed cooldown reduction % stat as it is unused',
          'fixed life steal, siege damage and cooldown reduction description labels showing their text ID instead of a proper text',
        ]),
        "removed preselection indicator from Probius' structures",
        "added low Health label into Probius' health bar",
        "removed non-functional death recap button above the player vision's death timer",
        new Change('fixed KillLog panel not being visible', [
          'known problem: vertical position is not using the upmost slot until you switch to player vision for the first time',
        ]),
      ]),
      new Change('added the talent icon to Talent tooltips, centered talent title', [
        'known problem: quest progress bar is currently hidden within the tooltip as the engine fails to properly copy its max value',
      ]),
      "removed preselection indicator from Lt. Morales' Medivac",
      'removed the colored ribbon from unit info panel as it is always red',
      "added Zul'jin's Guillotine damage into his hero UI. It is an approximation as it updates instantly while the real damage value updates only every 0.25s.",
      new Change('unit details panel changes:', [
        'added physical, spell armor and kill streak that hide if 0',
        'move speed hides if 100% or unit cannot move (e.g. structures)',
        'spell power, life steal, cooldown reduction hide if 0%',
        'fixed "stopped" and "stasis" buffs overlapping in the unit details panel',
        'added HinderedHealing debuff (e.g. inflicted by Varian)',
        "debuffs do not become instantly visible when the selected unit is switched (it still requires a game tick to reflect the unit's actual data)",
        "updated images for resistant and vulnerable to match the ones next to the heroes' health bar",
      ]),
      new Change("fixed background image hiding in Ragnaros' hero UI:", [
        'known problem: selection changes can cause the charge orbs to disappear and play a discharge animation',
      ]),
    ],
  } as Changelog,
  {
    id: '39',
    title: 'v.0.39 - Lúcio',
    image: ahliObs39,
    createdAt: '17th February 2017',
    download: 'https://www.dropbox.com/s/xvpni63mqqlztc4/AhliObs%20v.0.39.StormInterface?dl=1',
    version: '0.39',
    date: '17th February 2017',
    changes: [
      "fixed Zarya's Energy color (it did not match the one displayed above her model)",
      'quest talents on level 20 will now appear similar to other talents',
      new Change('added compatibility to Lúcio Update:', ["added Lúcio's hero UI"]),
    ],
  } as Changelog,
  {
    id: '38',
    title: '0.38 - Valeera',
    image: ahliObs38,
    createdAt: '25th January 2017',
    download: 'https://www.dropbox.com/s/adjoaf67b67wl01/AhliObs%20v.0.38.StormInterface?dl=1',
    version: '0.38',
    date: '25th January 2017',
    changes: [
      new Change('added compatibility to Valeera Update:', [
        'added new heroUI for Sonya, Malfurion, Tychus, Jaina, Valeera',
        'added new heroUI element for Li-Ming',
        "added Valeera's yellow Mana bar",
      ]),
    ],
  } as Changelog,
  {
    id: '37',
    title: "0.37 - Zul'jin",
    image: ahliObs37,
    createdAt: '4th January 2017',
    download: 'https://www.dropbox.com/s/wnn8protdyf17t0/AhliObs%20v.0.37.StormInterface?dl=1',
    version: '0.37',
    date: '4th January 2017',
    changes: [
      new Change("added compatibility to Zul'jin Update:", [
        "added Zul'Jin's hero UI",
        'added TimeStop debuff icon',
        'updated UnKillable debuff icon image',
      ]),
    ],
  } as Changelog,
  {
    id: '36',
    title: '0.36 - Ragnaros',
    image: ahliObs36,
    createdAt: '15th December 2016',
    download: 'https://www.dropbox.com/s/43xriswh1s7dux4/AhliObs%20v.0.36.StormInterface?dl=1',
    version: '0.36',
    date: '15th December 2016',
    changes: [
      new Change('bottom panel changes/fixes:', [
        'talent tooltips contain an image of the hero',
        "level progress bars in the talent tab adjust to Chromie's trait",
      ]),
      "flames behind the team level number, indicating a talent lead, now always ignore Chromie's trait (from 80% to 100% ignore chance)",
      'added hero UI for Arthas, Brightwing, Chen, Zeratul, Valla, Nova, Nazeebo, Illidan, Falstad, ETC and Diablo',
      new Change('added compatibility to Ragnaros Update:', ["added Ragnaros' hero UI"]),
    ],
  } as Changelog,
  {
    id: '35',
    title: '0.35 - Varian',
    image: ahliObs35,
    createdAt: '15th November 2016',
    download: 'https://www.dropbox.com/s/2tv0ea4yg6en13e/AhliObs%20v.0.35.StormInterface?dl=1',
    version: '0.35',
    date: '15th November 2016',
    changes: [
      new Change('unit info panel changes/fixes:', [
        "removed animation from Warhead Junction's Nuke Button Holder and positioned it better",
        "fixed Tracer's heroic ability ready ping size on the ability button in the unit info panel",
        'updated icon for taunt debuffs in unit details (Control+C)',
      ]),
      new Change('bottom panel changes/fixes:', [
        "added team's experience information to the bottom panel's experience tab",
        "fixed right side's portraits in bottom panel being vertically stretched",
        'fixed player vision altering progress bar textures in the bottom panel',
      ]),
      'during player vision, the talent panel now becomes visible when its hotkey is used',
      new Change('added compatibility to Varian Update:', [
        "fixed debuff icons' background image in the unit details",
        "fixed red team's level progress bar in bottom panel's talent overview appearing blue instead of red",
        "added Varian's hero UI",
      ]),
    ],
  } as Changelog,
  {
    id: '34',
    title: '0.34 - Samuro PTR',
    image: ahliObs34,
    createdAt: '11th October 2016',
    download: 'https://www.dropbox.com/s/4awqn95sgyflku9/AhliObs%20v.0.34.StormInterface?dl=1',
    version: '0.34',
    date: '11th October 2016',
    changes: [
      new Change("added compatibility to Auriel's patch", [
        "added Auriel's hero UI (not fully functional) and her colored mana bar",
        "Zarya's hitpoint amount will appear on her life bar when she is low",
        'added Nuke button with proper size to ability buttons',
        "added Zarya's hero UI",
        "added Samuro's hero UI",
      ]),
      new Change("bottom panel's changes:", [
        'portraits are not stretched anymore',
        'adjusted height of the background image',
        'added backgrounds for the column titles',
        'fixed time-CCed-enemy showing a wrong statistic',
        'fixed carried objective not being visible',
        'widened the role score field',
      ]),
      "Auriel's and Alarak's hero UI are now hidden as they were not fully functional",
    ],
  } as Changelog,
  {
    id: '33',
    title: '0.33 - Alarak',
    image: ahliObs33,
    createdAt: '13th September 2016',
    download: 'https://www.dropbox.com/s/1kiqg1ad16fg3la/AhliObs%20v.0.33.StormInterface?dl=1',
    version: '0.33',
    date: '13th September 2016',
    changes: ['redid the bottom panel'],
  } as Changelog,
  {
    id: '32',
    title: '0.32 - Auriel PTR',
    image: ahliObs32,
    createdAt: '2nd August 2016',
    download: 'https://www.dropbox.com/s/ekd43vwyohks6ra/AhliObs%20v.0.32.StormInterface?dl=1',
    version: '0.32',
    date: '2nd August 2016',
    changes: [
      new Change("added compatibility to Auriel's patch", [
        "added Auriel's hero UI (not fully functional) and her colored mana bar",
        "added Uther's hero UI",
      ]),
      'added animation to the hero portrait when the hero controls Dragon Knight / Plant Horror',
    ],
  } as Changelog,
  {
    id: '31',
    title: '0.31 - Guldan',
    image: ahliObs31,
    createdAt: '13th July 2016',
    download: 'https://www.dropbox.com/s/9spykxvfikuhw4m/AhliObs%20v.0.31.StormInterface?dl=1',
    version: '0.31',
    date: '13th July 2016',
    changes: [
      new Change("added compatibility to Guldan's patch", [
        'added feared and unkillable; fixed taunted status in unit details panel',
        'health bars of selected units are green again',
        "added Guldan's hero UI",
      ]),
      "Medivh's Portal's duration bar color is now orange instead of always blue",
      'added flames behind team level indicating talent lead',
      'damage over time is now drawn in dark yellow on all health bars',
    ],
  } as Changelog,
  {
    id: '30',
    title: '0.30 - Medivh',
    image: ahliObs30,
    createdAt: '18th June 2016',
    download: 'https://www.dropbox.com/s/6cr5g5p0qqls212/AhliObs%20v.0.30.StormInterface?dl=1',
    version: '0.30',
    date: '18th June 2016',
    changes: [
      new Change("added compatibility to Medivh's patch", [
        'fixed Health labels hiding while a unit is invulnerable',
        "re-enabled '?' icons for talents",
        "removed default UI's Tracer vertical charge bar with the circular one",
        "fixed Medivh's Raven form life bar not visible on red team, changed color to blue/red from green",
        "low Health Medivh's will now display their life value on the bar as the other Heroes",
      ]),
      new Change("fixed Tracer's charge counter in the info panel", [
        'charge counter will now always appear properly',
        'now supports having multiple Tracers and switching selection between them',
      ]),
      "fixed Tracer's low-life value on the life bar not appearing",
    ],
  } as Changelog,
  {
    id: '29',
    title: '0.29',
    createdAt: '22nd May 2016',
    download: 'https://www.dropbox.com/s/s22jgeilcsmwxmq/AhliObs%20v.0.29.StormInterface?dl=1',
    version: '0.29',
    date: '22nd May 2016',
    changes: ['fixed bottom panel talent icons being invisible until the talent panel was revealed the first time'],
  } as Changelog,
  {
    id: '28',
    title: '0.28',
    createdAt: '21st May 2016',
    download: 'https://www.dropbox.com/s/kbf3hweoyrjtiru/AhliObs%20v.0.28.StormInterface?dl=1',
    version: '0.28',
    date: '21st May 2016',
    changes: [
      ' bottom panel talent icons will now hide until the player selected one to overwhelm the viewers with ? icons',
    ],
  } as Changelog,
  {
    id: '27',
    title: '0.27',
    image: ahliObs27,
    createdAt: '19th May 2016',
    download: 'https://www.dropbox.com/s/43d5v76ibwh8dzg/AhliObs%20v.0.27.StormInterface?dl=1',
    version: '0.27',
    date: '19th May 2016',
    changes: [
      new Change('added compatibility to the new patch', [
        'fixed all talent icons being visible in the top panel',
        'fixed heroic icon positions in the top panel',
        "removed heroic cooldown's circular animation, replaced with darkening of the icon",
        new Change('fixed heroic icons only appear when they are used', [
          "the '?' symbol has been removed due to the default UI's states not working as intended",
          'known problem: the bar widths are not reset if you revert time in replays',
        ]),
        'fixed colored Mana bars in the top panel',
        new Change(' fixed talent positions and borders in the bottom panel', [
          'quest progress is now visible on the icon border',
          "the '?' icons are always visible due default UI's states not working as intended",
        ]),
        'added new status icon for rooted and mind-controlled to unit details panel',
      ]),
      "added missing low-life label in Tracer's life bar above her unit instance",
      new Change('added hotkeys to increase/decrease map scores', [
        'Ctrl+Shift+S to toggle the panel',
        "Alt+S to increase the blue team's score (or click on the number on screen)",
        "Alt+D to increase the red team's score (or click on the number on screen)",
        "Control+Alt+S to decrease the blue team's score",
        "Control+Alt+D to decrease the red team's score",
        new Change('To see "Red Team" / "Blue Team" labels as team names, click 5 times on the name panel', [
          "If you use the Logos.StormMod feature, clicking will cycle through the name+logo defined per team's player slot, too.",
        ]),
      ]),
      new Change('improved life and mana bar appearance in the top panel:', [
        "cut off the single pixel line at the bar's top side that ignores its transparency",
      ]),
    ],
  } as Changelog,
  {
    id: '26',
    title: '0.26',
    image: ahliObs26,
    createdAt: '25th April 2016',
    download: 'https://www.dropbox.com/s/gk5pd5eqof988bu/AhliObs%20v.0.26.StormInterface?dl=1',
    version: '0.26',
    date: '25th April 2016',
    changes: [
      'fixed activatable talent button positions',
      'removed death recap button again as clicking it does nothing and visibility does not update on player vision changes',
      new Change('Tracer:', [
        'heroic cooldown progress will now be shown near the portraits',
        'fixed charge counter disappearing in the unit info panel when at least two Tracers were in the game',
      ]),
    ],
  } as Changelog,
  {
    id: '25',
    title: '0.25',
    createdAt: '23rd April 2016',
    download: 'https://www.dropbox.com/s/oq0s5p80oua8vt1/AhliObs%20v.0.25.StormInterface?dl=1',
    version: '0.25',
    date: '23rd April 2016',
    changes: [
      'restored the death recap popup appearing in player vision when the player died',
      'added dehaka hero UI',
      new Change('Tracer:', [
        'fixed energy type displaying Mana instead of Ammunition',
        'fixed heroic cooldown on the ability button, but disabled animation for Blink button',
        "removed mana bar in the selected unit info, but added Tracer's weapon icon",
        "added pips to portrait's mana bar",
      ]),
    ],
  } as Changelog,
  {
    id: '24',
    title: '0.24',
    image: ahliObs24,
    createdAt: '29th March 2016',
    download: 'https://www.dropbox.com/s/hdwsfsv3o57dyhi/AhliObs%20v.0.24.StormInterface?dl=1',
    version: '0.24',
    date: '29th March 2016',
    changes: [
      'death recap button moved offscreen as it was able to permanently stay on screen when observed a death with player vision',
      'fixed Ammunition label being displayed above Mana when no tower/fort/keep was selected so far',
      'when a hero falls below 15% life for 1-2 seconds, its hitpoint value will be displayed inside the health bar',
    ],
  } as Changelog,
  {
    id: '23',
    title: '0.23',
    image: ahliObs23,
    createdAt: '22nd March 2016',
    download: 'https://www.dropbox.com/s/6wb4imzlwnn8ljq/AhliObs%20v.0.23.StormInterface?dl=1',
    version: '0.23',
    date: '22nd March 2016',
    changes: [
      'redesigned the top panel',
      'removed heroics on the side of the screen and its hotkey',
      'added intro animations',
      "improved fade speed of the bottom panel's tab animations",
      "portrait icon's mouse hit zone now matches the icon instead of being rectangular",
      "fixed activatable talents' cooldown showing '...'",
      "fixed ability charge counter's cooldown image being cut off and reduced its size",
      "added Li-Ming's hero UI",
      "added Xul's hero UI",
      "fixed Greymane's hero UI size and position",
      "behavior bar's glass is now only showing when a buff icon is displayed",
      "buff icon's mouse hit zone now matches the icon instead of being rectangular",
      'fixed Control+Alt+U not hiding effects on the minimap',
      new Change('added new hotkey Control+E to hide most UI elements, but not health bars in the game world', [
        'this should be good for highlight videos where UI should be hidden, but health bars be visible',
      ]),
      're-added panel with stats for a selected unit (hotkey: Control+C)',
      new Change("added yellow highlight to bottom panel's talent icon borders when interacting with the mouse", [
        'this should help viewers to keep track which talent a caster is talking about',
      ]),
      "Lost Viking's numbers above the health bars are now hidden in their player vision",
      'pause notifications moved downwards, received a new look and its text is now centered',
      new Change('map score panel has been re-added (Control+Shift+S)', [
        'cycle through six team names and ten score values via mouse clicks',
        'all five team names defined by the player slot are now empty unless Logos mod defines one',
        'added a new 6th team generic team name (Blue Team/Red Team); click five times on the name area to reach it',
        "undefined logos now have a width of 1 pixel to reduce the impact on the name label's size",
      ]),
      'fixed control+W making the old xp-bar and its background image appear',
      'fixed control+W making the old core life bars and its background images appear',
      'established compatibility with the new patch',
    ],
  } as Changelog,
  {
    id: '22',
    title: '0.22',
    image: ahliObs22,
    createdAt: '6th February 2016',
    download: 'https://www.dropbox.com/s/po231prlkxm7vwt/AhliObs%20v.0.22.StormInterface?dl=1',
    version: '0.22',
    date: '6th February 2016',
    changes: [
      'added compatibility to the new patch',
      'removed pre-selection highlight on all health bars',
      'removed mechanic score in bottom panel as it was always empty for some time',
      'removed objective UI changes in Garden of Terror',
      'removed my gem/coin counter',
      'disabled the map score panel',
      'added a small buff display for selected units if unit info field is hidden (Ctrl + Alt + K)',
    ],
  } as Changelog,
  {
    id: '21',
    title: '0.21',
    image: ahliObs21,
    createdAt: '18th November 2015',
    download: 'https://www.dropbox.com/s/b1nm4fmoesjmu12/AhliObs%20v.0.21.StormInterface?dl=1',
    version: '0.21',
    date: '18th November 2015',
    changes: [
      'added compatibility to the new patch',
      'fixed unequal width of Kills, Assists, Deaths in bottom panel',
      'added best value-per-team-highlighting to kills and assists in bottom panel',
      'removed best value-per-team-highlighting from time-spent-dead as that is actually the worst value',
      "rearranged the order of kills, deaths, assists in bottom panel to this order matching Blizz's TAB window",
      'updated CN and TW locales',
    ],
  } as Changelog,
  {
    id: '20',
    title: '0.20',
    image: ahliObs20,
    createdAt: '15th November 2015',
    download: 'https://www.dropbox.com/s/3tf7i8v7nj2m85s/AhliObs%20v.0.20.StormInterface?dl=1',
    version: '0.20',
    date: '15th November 2015',
    changes: [
      'added compatibility to the new patch based on the PTR',
      new Change('improved visual appearance depending if the game is live or replay', [
        'replay controls hotkey only needs to be pressed once',
      ]),
      'fixed heroics sometimes disappearing from screen',
      'on level 10, the heroic icons now slide in instead of popping up instantly',
      new Change('heroic cooldown changes:', [
        'replaced buggy animated cooldown image behind the cooldown text with a static grey image',
        'the borders are now dimmed when the heroic is on cooldown',
        'now the font has an outline',
        'tooltips now appear in the inner bottom corner in order to not overlap',
      ]),
      'Added Kills, Assists and Deaths to bottom panel (hotkey: Ctrl+Shift+7)',
      "Healing Fountain's cooldown is now hidden for most units not owned by the heroes",
    ],
  } as Changelog,
  {
    id: '19',
    title: '0.19',
    createdAt: '6th October 2015',
    download: 'https://www.dropbox.com/s/sy49kiwopothsrl/AhliObs%20v.0.19.StormInterface?dl=1',
    version: '0.19',
    date: '6th October 2015',
    changes: [
      new Change('replay panel changes:', [
        'it is now hidden in live games and visible in replays by default',
        'added pulldown for player vision',
      ]),
      'reduced file size due to better MPQ compression',
      "reverted health bar's pre-selection-highlighting to Blizzard's settings",
      new Change('added compatibility to the new patch based on the PTR', [
        'fixed ability and talent button appearance',
        'fixed new behavior display',
        'fixed border texture of life and mana bar in bottom left',
        'fixed placement of life/mana value labels',
        'fixed bottom panel tab showing self healing listing damage stats, too',
      ]),
      new Change('for your information, Blizzard added new hotkeys for Observers:', [
        'o - Follow an Observer',
        "w - Jump into vision of the selected unit's player",
      ]),
    ],
  } as Changelog,
  {
    id: '18',
    title: '0.18',
    image: ahliObs18,
    createdAt: '12th August 2015',
    download: 'https://www.dropbox.com/s/0byjyrp9br1wt76/AhliObs%20v.0.18.StormInterface?dl=1',
    version: '0.18',
    date: '12th August 2015',
    changes: [
      new Change('added compatibility to the new patch based on the PTR', [
        'fixed ability and talent buttons',
        'fixed missing life bar background',
        'fixed version string not appearing in the UI settings dialog (click below timer to access)',
      ]),
      'fixed UI settings dialog and its button being stretched with resolution changes',
    ],
  } as Changelog,
  {
    id: '17',
    title: '0.17',
    image: ahliObs17,
    createdAt: '11th August 2015',
    download: 'https://www.dropbox.com/s/44u71lsxiofopqk/AhliObs%20v.0.17.StormInterface?dl=1',
    version: '0.17',
    date: '11th August 2015',
    changes: [
      "fixed Garden of Terror's seed counter animation fading the wrong team's count label",
      new Change('added a better implementation for colored mana bars', [
        '-> more FPS with enabled mature language filter, no resolution bugs, full support with every language',
        'removed the huge intro watermark',
      ]),
    ],
  } as Changelog,
  {
    id: '16',
    title: '0.16',
    createdAt: '4th July 2015',
    download: 'https://www.dropbox.com/s/90wc0mmih5yxke2/AhliObs%20v.0.16.StormInterface?dl=1',
    version: '0.16',
    date: '4th July 2015',
    changes: [
      'fixed Thrall displaying a non-functional trait UI element',
      'fixed a bug preventing the heroics at the sides of the screen to not re-appear when toggled',
      'game tooltips are now forced to be enabled',
      'fixed long unit names being displayed in a second row instead of being cut off',
    ],
  } as Changelog,
  {
    id: '0.15',
    title: '0.15',
    image: ahliObs15,
    createdAt: '1st July 2015',
    download: 'https://www.dropbox.com/s/wctc72fwywp4mwm/AhliObs%20v.0.15.StormInterface?dl=1',
    version: '0.15',
    date: '1st July 2015',
    changes: [
      'updated Chinese and Taiwanese translations (by twitter @tinkoliu)',
      'reapplied my size fix for heroic cooldown labels in the TAB-window',
      'fixed hero specific elements from the default UI becoming visible when you press 1-0',
      "added Butcher's meat stack counter when selected",
      "fixed TAB hotkey being hardcoded. Now it is using the game's hotkey setting again. (Blizzard's underlying bug is still present, I have only created a better workaround.)",
      "improved bottom panel's looks (graphics, portraits will not become transparent on death anymore)",
    ],
  } as Changelog,
  {
    id: '14',
    title: '0.14',
    image: ahliObs14,
    createdAt: '30th June 2015',
    download: 'https://www.dropbox.com/s/9v9pa3zf50199dt/AhliObs%20v.0.14.StormInterface?dl=1',
    version: '0.14',
    date: '30th June 2015',
    changes: [
      'added compatibility to the new patch based on the PTR',
      'fixed an issue that made features like the replay panel disappear',
      'added a constant that allows you to move the entire UI upwards',
    ],
  } as Changelog,
  {
    id: '13',
    title: '0.13',
    createdAt: '20th May 2015',
    download: 'https://www.dropbox.com/s/oiz5kuvgvvb5qw6/AhliObs%20v.0.13.StormInterface?dl=1',
    version: '0.13',
    date: '20th May 2015',
    changes: [
      'added UI dialog allowing you to alter interface settings and look up hotkeys. Click below the map timer to show it.',
      new Change(
        'added a map score panel between the experience bars and the portraits. Click on the score or name to cycle through them.',
        [
          'the team name and logo are read from "Logos.StormMod" and depending on the selected data set in the lobby.',
          'more information about that mod will come in future',
        ]
      ),
    ],
  } as Changelog,
  {
    id: '12',
    title: '0.12',
    createdAt: '17th May 2015',
    download: 'https://www.dropbox.com/s/5wu73d5hkunse5m/AhliObs%20v.0.12.StormInterface?dl=1',
    version: '0.12',
    date: '17th May 2015',
    changes: [
      'fixed activatable talents flickering on screen',
      'fixed some UI problems which only appeared on some maps (Core life bars on HUD, replay control buttons, partial fix of the ability buttons)',
    ],
  } as Changelog,
  {
    id: '11',
    title: '0.11',
    image: ahliObs11,
    createdAt: '15th May 2015',
    download: 'https://www.dropbox.com/s/tiegs0bkd5lycyn/AhliObs%20v.0.11.StormInterface?dl=1',
    version: '0.11',
    date: '15th May 2015',
    changes: ['established full compatibility with the most recent Heroes patch'],
  } as Changelog,
  {
    id: '10',
    title: '0.10',
    createdAt: '13th May 2015',
    download: 'https://www.dropbox.com/s/ofv3c9i70uq702t/AhliObs%20v.0.10a.StormInterface?dl=1',
    version: '0.10',
    date: '13th May 2015',
    changes: [
      'first update fixing some of the problems caused by the recent patch. The patch updated the UI and how some frames behave causing major havoc in my UI.',
    ],
  } as Changelog,
  {
    id: '9',
    title: '0.09',
    createdAt: '18th April 2015',
    download: 'https://www.dropbox.com/s/mr4g9bt4wc9o38c/AhliObs%20v.0.09.StormInterface?dl=1',
    version: '0.09',
    date: '18th April 2015',
    changes: [
      "removed the experience panel's zero values",
      'Garden of Terror: seed counter is now alternating with the status label ("Growing") while the plant grows or awaits a passenger',
      'added hotkey to hide the information about the selected unit called Khaldor Mode. Hotkey: CTRL + Alt + K',
      'blocked hotkeys CTRL + 7/8/9/0 to avoid accidential hero selection',
    ],
  } as Changelog,
  {
    id: '8',
    title: '0.08',
    createdAt: '27th March 2015',
    download: 'https://www.dropbox.com/s/hnrjaosc58jpqf2/AhliObs%20v.0.08.StormInterface?dl=1',
    version: '0.08',
    date: '27th March 2015',
    changes: ['added hotkey to hide all UI elements: Control + Alt + U'],
  } as Changelog,
  {
    id: '7',
    title: '0.07',
    createdAt: '',
    download: 'https://www.dropbox.com/s/y5jv82kbutd4mxo/AhliObs%20v.0.07.StormInterface?dl=1',
    version: '0.07',
    date: '',
    changes: [
      'fixed "XP Contribution" text in the bottom panel. Now it is labelled as "XP Total" again.',
      'fixed the upmost line in the chat being half-cut off (patch altered something like using a smaller font size, I guess)',
      'added information about the currently carried objective amount of each team into the infobar below the portraits',
      'unused activatable talent buttons are now hidden again (patch made them always visible, so players can drag abilities everywhere I assume)',
      'fixed replay bar overlapping with the selected-unit-information (patch changed the replay bar, especially the button size)',
    ],
  } as Changelog,
  {
    id: '6',
    title: '0.06',
    createdAt: '25th March 2015',
    download: 'https://www.dropbox.com/s/bp6xvjm9i13fktk/AhliObs%20v.0.06.StormInterface?dl=1',
    version: '0.06',
    date: '25th March 2015',
    changes: [
      'added translation for Taiwanese (by twitter @tinkoliu)',
      'improved text size in the Chinese and Taiwanese version',
    ],
  } as Changelog,
  {
    id: '5',
    title: '0.05',
    image: ahliObs5,
    createdAt: '17th February 2015',
    download: 'https://www.dropbox.com/s/44kq1z8a17dwwxy/AhliObs%20v.0.05.StormInterface?dl=1',
    version: '0.05',
    date: '17th February 2015',
    changes: [
      "removed tooltip of carried gold on the hero (I've failed in the last version)",
      'started to clean up the unit pre-selection (health bar becomes brighter, if mouse is above a unit)',
      'moved the control group panel offscreen (Lost Vikings use that panel to alter the hero selection)',
      'added fury and brew bar for most languages (Chinese and Korean have only blue bars, Taiwanese has a blue brew bar)',
      'fixed Chinese text being displayed in other languages',
    ],
  } as Changelog,
  {
    id: '4',
    title: '0.04',
    createdAt: '8th February 2015',
    download: 'https://www.dropbox.com/s/j0j0il3a4purk3m/AhliObs%20v.0.04.StormInterface?dl=1',
    version: '0.04',
    date: '8th February 2015',
    changes: [
      'added compression to the file (804kb -> 58kb)',
      "fixed layering problem with the unit info's background image, also slightly altered the image (removed edge in the top left), fixed overlapping with replay panel",
      "fixed Heroic-Talents-at-the-Sides' toggle (Ctrl + Shift + T) not working correctly",
      'fixed cooldown label position on mount/hearthstone button',
      'changed mana and life bar positions in the team areas',
      'added Chinese localization',
      'removed tooltip of carried gold on the hero (last patch added that, I assume)',
    ],
  } as Changelog,
  {
    id: '3',
    title: '0.03',
    image: ahliObs3,
    createdAt: '4th February 2015',
    download: 'https://www.dropbox.com/s/3t8xwoz4hp7a95t/AhliObs%20v.0.03.StormInterface?dl=1',
    version: '0.03',
    date: '4th February 2015',
    changes: [
      'removed ping button',
      'improved bar colors in hero overview panel',
      'solved player vision hiding activatable talent buttons',
      'added background image to the selected unit info area',
      'improved size and spacing of inventory and talent buttons',
      "removed the bars when you select multiple Heroes. I want to show just a single unit's stats then, but there is a problem right now, so this is disabled.",
      'removed Core Health Label. Streamers can now easily put their league/organization logo in the center top area',
    ],
  } as Changelog,
  {
    id: '2',
    title: '0.02',
    createdAt: '15th January 2015',
    version: '0.03',
    date: '15th January 2015',
    changes: [
      "level 10 talents are now visible from the map's start, you don't need to press ctrl+shift+T anymore",
      'added owner indicator for single selected units next to the life bar',
      'added mana bar to the hero portraits at the top',
      'added a panel with life and mana values that appears when you hover over a portrait for short moment (WIP, it looks bad atm, will improve).',
      'the attack damage display will now disappear, if the selected unit has 0 attack damage',
      new Change('player vision changes:', [
        'player vision does not make two buff/debuff panels appear anymore',
        'the bottom center panel is now hidden during player vision',
        'player vision does not hide the ability buttons anymore',
        "a heroes' stun and channel bar are now anchored to the bottom of the screen instead of moving up/downwards with the ability buttons when the replay controls toggle is used",
      ]),
      "fixed ability buttons' charge label appearing somewhere else",
      'fixed recent heroes patch making the Tab hotkey refer to my talent overview panel',
    ],
  } as Changelog,
  {
    id: '1',
    title: '0.01',
    image: ahliObs1,
    createdAt: '3rd January 2015',
    version: '0.01',
    date: '3rd January 2015',
    changes: ['initial release'],
  } as Changelog,
];
