-- DO NOT EDIT THIS FILE AFTER CREATION! DETECTION USES CHECKSUM!

-- create hibernate's default sequence
CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START WITH 1 INCREMENT BY 1;


CREATE TABLE IF NOT EXISTS rule_set (
    id BIGINT NOT NULL PRIMARY KEY
                       -- PRIMARY KEY is set here because H2 does not seem to have a good primary key constraint check
);
CREATE TABLE IF NOT EXISTS project (
    id BIGINT NOT NULL PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    project_path VARCHAR(255) NOT NULL,
    game VARCHAR(8) NOT NULL,
    last_build_date TIMESTAMP,
    last_build_size BIGINT,
    best_compression_rule_set_id BIGINT
);
CREATE TABLE IF NOT EXISTS rule_set_compression_rules_string (
    rule_set_id BIGINT NOT NULL,
    compression_rules_string VARCHAR(255)
);

-- drop constraints created by hibernate
ALTER TABLE project DROP CONSTRAINT IF EXISTS FKhm3umvvq62rcdxsu12eucu7r0;
ALTER TABLE project DROP CONSTRAINT IF EXISTS UK_kyfcexjac0nlp72bwi01pqymy;
ALTER TABLE project DROP PRIMARY KEY;
ALTER TABLE rule_set_compression_rules_string DROP CONSTRAINT IF EXISTS FKlqo8ibggfmonkwlvlt62vj9yl;
ALTER TABLE rule_set DROP PRIMARY KEY;

-- convert data types
ALTER TABLE project ALTER COLUMN id BIGINT NOT NULL;

-- add new constrains with readable names
ALTER TABLE project ADD CONSTRAINT PK_project PRIMARY KEY (id);
ALTER TABLE rule_set ADD CONSTRAINT PK_rule_set PRIMARY KEY (id);
ALTER TABLE project ADD CONSTRAINT UC_project UNIQUE (project_path);
ALTER TABLE project ADD CONSTRAINT FK_project_rule_set
    FOREIGN KEY (best_compression_rule_set_id) REFERENCES rule_set(id);
ALTER TABLE rule_set_compression_rules_string ADD CONSTRAINT FK_rule_set_compression_rules_string_rule_set
    FOREIGN KEY (rule_set_id) REFERENCES rule_set(id);


