name: Check XML

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  check:
    name: Check Syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Verify XML files
        uses: Ahli/verify-xml-action@v1
        with:
          path: ""
          file-endings: ".xml,.SC2Components, DocumentInfo, .SC2Style, SC2Layout, .StormComponents, .StormLayout, .StormStyle, .StormCutscene, .SC2Cutscene"
